In [1]:
import polars as pl
import pandas as pd
import time

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
pl_df = pl.read_csv("teen_phone_addiction_dataset.csv")

print(pl_df.head())
print(pl_df.shape)

shape: (5, 25)
┌─────┬──────────────┬─────┬────────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ ID  ┆ Name         ┆ Age ┆ Gender ┆ … ┆ Phone_Usage_ ┆ Family_Commu ┆ Weekend_Usag ┆ Addiction_L │
│ --- ┆ ---          ┆ --- ┆ ---    ┆   ┆ Purpose      ┆ nication     ┆ e_Hours      ┆ evel        │
│ i64 ┆ str          ┆ i64 ┆ str    ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│     ┆              ┆     ┆        ┆   ┆ str          ┆ i64          ┆ f64          ┆ f64         │
╞═════╪══════════════╪═════╪════════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 1   ┆ Shannon      ┆ 13  ┆ Female ┆ … ┆ Browsing     ┆ 4            ┆ 8.7          ┆ 10.0        │
│     ┆ Francis      ┆     ┆        ┆   ┆              ┆              ┆              ┆             │
│ 2   ┆ Scott        ┆ 17  ┆ Female ┆ … ┆ Browsing     ┆ 2            ┆ 5.3          ┆ 10.0        │
│     ┆ Rodriguez    ┆     ┆        ┆   ┆              ┆              ┆              ┆             │
│ 3   ┆ Adrian Knox  ┆ 13  ┆ Other  ┆ … ┆ Education    ┆ 6            ┆ 5.7          ┆ 9.2         │
│ 4   ┆ Brittany     ┆ 18  ┆ Female ┆ … ┆ Social Media ┆ 8            ┆ 3.0          ┆ 9.8         │
│     ┆ Hamilton     ┆     ┆        ┆   ┆              ┆              ┆              ┆             │
│ 5   ┆ Steven Smith ┆ 14  ┆ Other  ┆ … ┆ Gaming       ┆ 10           ┆ 3.7          ┆ 8.6         │
└─────┴──────────────┴─────┴────────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘
(3000, 25)

In [3]:
print(pl_df.schema)

Schema([('ID', Int64), ('Name', String), ('Age', Int64), ('Gender', String), ('Location', String), ('School_Grade', String), ('Daily_Usage_Hours', Float64), ('Sleep_Hours', Float64), ('Academic_Performance', Int64), ('Social_Interactions', Int64), ('Exercise_Hours', Float64), ('Anxiety_Level', Int64), ('Depression_Level', Int64), ('Self_Esteem', Int64), ('Parental_Control', Int64), ('Screen_Time_Before_Bed', Float64), ('Phone_Checks_Per_Day', Int64), ('Apps_Used_Daily', Int64), ('Time_on_Social_Media', Float64), ('Time_on_Gaming', Float64), ('Time_on_Education', Float64), ('Phone_Usage_Purpose', String), ('Family_Communication', Int64), ('Weekend_Usage_Hours', Float64), ('Addiction_Level', Float64)])

In [4]:
pl_df.select([
    "Daily_Usage_Hours",
    "Academic_Performance"
]).head()

shape: (5, 2)
┌───────────────────┬──────────────────────┐
│ Daily_Usage_Hours ┆ Academic_Performance │
│ ---               ┆ ---                  │
│ f64               ┆ i64                  │
╞═══════════════════╪══════════════════════╡
│ 4.0               ┆ 78                   │
│ 5.5               ┆ 70                   │
│ 5.8               ┆ 93                   │
│ 3.1               ┆ 78                   │
│ 2.5               ┆ 56                   │
└───────────────────┴──────────────────────┘

In [5]:
pl_df.filter(
    pl.col("Daily_Usage_Hours") > 5
)

shape: (1_455, 25)
┌──────┬──────────────┬─────┬────────┬───┬──────────────┬──────────────┬─────────────┬─────────────┐
│ ID   ┆ Name         ┆ Age ┆ Gender ┆ … ┆ Phone_Usage_ ┆ Family_Commu ┆ Weekend_Usa ┆ Addiction_L │
│ ---  ┆ ---          ┆ --- ┆ ---    ┆   ┆ Purpose      ┆ nication     ┆ ge_Hours    ┆ evel        │
│ i64  ┆ str          ┆ i64 ┆ str    ┆   ┆ ---          ┆ ---          ┆ ---         ┆ ---         │
│      ┆              ┆     ┆        ┆   ┆ str          ┆ i64          ┆ f64         ┆ f64         │
╞══════╪══════════════╪═════╪════════╪═══╪══════════════╪══════════════╪═════════════╪═════════════╡
│ 2    ┆ Scott        ┆ 17  ┆ Female ┆ … ┆ Browsing     ┆ 2            ┆ 5.3         ┆ 10.0        │
│      ┆ Rodriguez    ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
│ 3    ┆ Adrian Knox  ┆ 13  ┆ Other  ┆ … ┆ Education    ┆ 6            ┆ 5.7         ┆ 9.2         │
│ 7    ┆ Hailey Moses ┆ 16  ┆ Male   ┆ … ┆ Education    ┆ 7            ┆ 7.8         ┆ 10.0        │
│ 8    ┆ Veronica     ┆ 13  ┆ Other  ┆ … ┆ Browsing     ┆ 9            ┆ 8.0         ┆ 8.0         │
│      ┆ Marshall     ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
│ 13   ┆ Sarah Nguyen ┆ 19  ┆ Female ┆ … ┆ Gaming       ┆ 8            ┆ 9.1         ┆ 10.0        │
│ …    ┆ …            ┆ …   ┆ …      ┆ … ┆ …            ┆ …            ┆ …           ┆ …           │
│ 2989 ┆ Angela Lyons ┆ 14  ┆ Male   ┆ … ┆ Education    ┆ 10           ┆ 7.5         ┆ 10.0        │
│ 2990 ┆ Christine    ┆ 18  ┆ Other  ┆ … ┆ Browsing     ┆ 6            ┆ 6.8         ┆ 8.4         │
│      ┆ Davenport    ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
│ 2992 ┆ Christina    ┆ 16  ┆ Male   ┆ … ┆ Social Media ┆ 8            ┆ 6.6         ┆ 9.6         │
│      ┆ Davila       ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
│ 2994 ┆ Sandra       ┆ 17  ┆ Other  ┆ … ┆ Social Media ┆ 2            ┆ 7.4         ┆ 10.0        │
│      ┆ Acevedo      ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
│ 2999 ┆ Barbara      ┆ 17  ┆ Female ┆ … ┆ Browsing     ┆ 4            ┆ 6.1         ┆ 10.0        │
│      ┆ Hinton       ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
└──────┴──────────────┴─────┴────────┴───┴──────────────┴──────────────┴─────────────┴─────────────┘

In [6]:
pl_df.sort(
    "Daily_Usage_Hours",
    descending=True
).head(10)

shape: (10, 25)
┌──────┬──────────────┬─────┬────────┬───┬──────────────┬──────────────┬─────────────┬─────────────┐
│ ID   ┆ Name         ┆ Age ┆ Gender ┆ … ┆ Phone_Usage_ ┆ Family_Commu ┆ Weekend_Usa ┆ Addiction_L │
│ ---  ┆ ---          ┆ --- ┆ ---    ┆   ┆ Purpose      ┆ nication     ┆ ge_Hours    ┆ evel        │
│ i64  ┆ str          ┆ i64 ┆ str    ┆   ┆ ---          ┆ ---          ┆ ---         ┆ ---         │
│      ┆              ┆     ┆        ┆   ┆ str          ┆ i64          ┆ f64         ┆ f64         │
╞══════╪══════════════╪═════╪════════╪═══╪══════════════╪══════════════╪═════════════╪═════════════╡
│ 2671 ┆ Deborah      ┆ 16  ┆ Other  ┆ … ┆ Browsing     ┆ 5            ┆ 4.8         ┆ 10.0        │
│      ┆ Gonzalez     ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
│ 2401 ┆ Lisa         ┆ 13  ┆ Male   ┆ … ┆ Browsing     ┆ 5            ┆ 8.2         ┆ 10.0        │
│      ┆ Gonzalez     ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
│ 711  ┆ Pamela       ┆ 15  ┆ Male   ┆ … ┆ Browsing     ┆ 8            ┆ 6.2         ┆ 10.0        │
│      ┆ Johnson      ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
│ 2747 ┆ Miranda Lee  ┆ 15  ┆ Male   ┆ … ┆ Social Media ┆ 5            ┆ 4.1         ┆ 10.0        │
│ 1666 ┆ Brian Pierce ┆ 15  ┆ Other  ┆ … ┆ Other        ┆ 5            ┆ 6.1         ┆ 10.0        │
│ 228  ┆ Michael      ┆ 18  ┆ Female ┆ … ┆ Other        ┆ 8            ┆ 6.3         ┆ 10.0        │
│      ┆ Hopkins      ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
│ 882  ┆ Bridget      ┆ 18  ┆ Other  ┆ … ┆ Education    ┆ 1            ┆ 7.4         ┆ 10.0        │
│      ┆ Santos       ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
│ 1732 ┆ Patrick      ┆ 14  ┆ Female ┆ … ┆ Browsing     ┆ 7            ┆ 3.5         ┆ 10.0        │
│      ┆ Adams        ┆     ┆        ┆   ┆              ┆              ┆             ┆             │
│ 2751 ┆ Jamie Salas  ┆ 15  ┆ Female ┆ … ┆ Other        ┆ 7            ┆ 2.5         ┆ 10.0        │
│ 583  ┆ Julia Rogers ┆ 16  ┆ Female ┆ … ┆ Social Media ┆ 10           ┆ 3.7         ┆ 10.0        │
└──────┴──────────────┴─────┴────────┴───┴──────────────┴──────────────┴─────────────┴─────────────┘

In [7]:
pl_df.group_by("Gender").agg(
    pl.col("Daily_Usage_Hours").mean().alias("Average_Usage")
)

shape: (3, 2)
┌────────┬───────────────┐
│ Gender ┆ Average_Usage │
│ ---    ┆ ---           │
│ str    ┆ f64           │
╞════════╪═══════════════╡
│ Other  ┆ 4.952508      │
│ Male   ┆ 5.054626      │
│ Female ┆ 5.052532      │
└────────┴───────────────┘

In [8]:
pl_df.select([
    pl.col("Daily_Usage_Hours").mean().alias("Average Usage"),
    pl.col("Daily_Usage_Hours").max().alias("Maximum Usage"),
    pl.col("Daily_Usage_Hours").min().alias("Minimum Usage")
])

shape: (1, 3)
┌───────────────┬───────────────┬───────────────┐
│ Average Usage ┆ Maximum Usage ┆ Minimum Usage │
│ ---           ┆ ---           ┆ ---           │
│ f64           ┆ f64           ┆ f64           │
╞═══════════════╪═══════════════╪═══════════════╡
│ 5.020667      ┆ 11.5          ┆ 0.0           │
└───────────────┴───────────────┴───────────────┘

In [9]:
import time

# Pandas benchmark
pandas_df = pd.read_csv("teen_phone_addiction_dataset.csv")

start = time.time()
pandas_df["Daily_Usage_Hours"].mean()
pandas_time = time.time() - start

# Polars benchmark
start = time.time()
pl_df.select(pl.col("Daily_Usage_Hours").mean())
polars_time = time.time() - start

print(f"Pandas Time: {pandas_time:.6f} seconds")
print(f"Polars Time: {polars_time:.6f} seconds")

Pandas Time: 0.004250 seconds
Polars Time: 0.000523 seconds